name: flutter_workoutkit
description: "A Flutter plugin that leverages Apple's WorkoutKit SDK to create, preview, and sync custom workouts with the Apple Watch Workout app."
version: 0.0.3
homepage: https://github.com/adamk22/flutter-workoutkit
issue_tracker: https://github.com/adamk22/flutter-workoutkit/issues

environment:
  sdk: ^3.5.4
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: WorkoutkitPlugin
